import {products,magnetPrices} from './data/products.js';
import {reviews} from './data/reviews.js';
const UPI='shilpa.k1994.sk-1@okaxis',WA='919071185948';let category='All',cart=JSON.parse(localStorage.getItem('pp_cart')||'[]'),payment='cod';
const $=id=>document.getElementById(id),money=n=>'₹'+Number(n).toLocaleString('en-IN');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function save(){localStorage.setItem('pp_cart',JSON.stringify(cart));$('count').textContent=cart.reduce((a,x)=>a+x.qty,0)}
function totals(){let sub=cart.reduce((a,x)=>a+x.price*x.qty,0);return{sub,shipping:sub?(sub>=999?0:99):0,total:sub+(sub>=999?0:sub?99:0)}}
function tabs(){return ['All','Customized','Accessories','Games','Kids'].map(c=>`<button class="tab ${category===c?'active':''}" data-cat="${c}">${c}</button>`).join('')}
function render(){let q=($('search').value||'').toLowerCase();$('tabs').innerHTML=tabs();document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{category=b.dataset.cat;render()});let list=products.filter(p=>(category==='All'||p.category===category)&&(`${p.name} ${p.description} ${p.category}`).toLowerCase().includes(q));$('products').innerHTML=list.map(p=>`<article class="product"><div class="product-photo"><img src="${p.image}" alt="${esc(p.name)}" loading="lazy">${p.badge?`<span class="badge">${esc(p.badge)}</span>`:''}</div><div class="product-info"><div class="category">${p.category}</div><div class="product-name">${esc(p.name)}</div><div class="product-desc">${esc(p.description)}</div><div class="product-bottom"><div class="price">${money(p.price)}${p.min?'<small style="font:10px Inter;color:#777"> /pc</small>':''}</div><button class="add" data-id="${p.id}">${p.min?'Select':'Add'} +</button></div></div></article>`).join('');$('price-list').innerHTML=magnetPrices.map(x=>`<div><span>${x[0]}</span><b>${money(x[1])}</b></div>`).join('');document.querySelectorAll('.add').forEach(b=>b.onclick=()=>add(+b.dataset.id))}
function renderReviews(){$('review-grid').innerHTML=reviews.map(r=>`<article class="review"><div class="stars">${'★'.repeat(r.rating)}</div><p>“${esc(r.text)}”</p><b>— ${esc(r.name)}</b></article>`).join('')}
function add(id){let p=products.find(x=>x.id===id),step=p.min||1,x=cart.find(a=>a.id===id);x?x.qty+=step:cart.push({id,qty:step,price:p.price});save();openCart()}
function cartView(){if(!cart.length){$('cart-items').innerHTML='<div style="text-align:center;color:#777;padding:70px 0">🛍️<br><br>Your cart is waiting for something beautiful.</div>';$('cart-footer').innerHTML='';return}$('cart-items').innerHTML=cart.map(x=>{let p=products.find(y=>y.id===x.id);return `<div class="cart-item"><img src="${p.image}" alt=""><div><b>${esc(p.name)}</b><small style="display:block;color:#777">${money(x.price)} each</small><div class="qty"><button onclick="changeQty(${x.id},-1)">−</button>${x.qty}<button onclick="changeQty(${x.id},1)">+</button></div></div><button onclick="removeItem(${x.id})" style="border:0;background:none;font-size:20px">×</button></div>`}).join('');$('cart-footer').innerHTML=`<div style="display:flex;justify-content:space-between;margin:15px 0"><span>Total</span><b>${money(totals().total)}</b></div><button class="btn btn-gold" style="width:100%" onclick="openCheckout()">Proceed to Checkout →</button>`}
window.changeQty=(id,d)=>{let x=cart.find(a=>a.id===id),p=products.find(a=>a.id===id);x.qty+=d;if(x.qty<(p.min||1))x.qty=p.min||1;if(x.qty>50)x.qty=50;save();cartView()};window.removeItem=id=>{cart=cart.filter(x=>x.id!==id);save();cartView()};
function openCart(){cartView();$('cart-drawer').classList.add('open')}window.openCart=openCart;function closeCart(){$('cart-drawer').classList.remove('open')}
window.openCheckout=()=>{if(!cart.length)return;closeCart();$('summary').innerHTML=`<div style="background:#f5efe6;padding:16px;border-radius:14px;margin-bottom:18px"><b>Order Summary</b><p style="font-size:12px;color:#777">${cart.map(x=>{let p=products.find(y=>y.id===x.id);return `${esc(p.name)} × ${x.qty} — ${money(x.price*x.qty)}`}).join('<br>')}</p><b>Grand Total: ${money(totals().total)}</b></div>`;$('checkout-modal').classList.add('open');updatePayment()};
function closeCheckout(){$('checkout-modal').classList.remove('open')}
function updatePayment(){$('cod').classList.toggle('selected',payment==='cod');$('upib').classList.toggle('selected',payment==='upi');$('upibox').classList.toggle('hidden',payment!=='upi');if(payment!=='upi')return;let amount=totals().total,link=`upi://pay?pa=${encodeURIComponent(UPI)}&pn=Present%20Perfect&am=${amount.toFixed(2)}&cu=INR&tn=Present%20Perfect%20Order`;$('upid').textContent=UPI;$('upiamt').textContent='Amount: '+money(amount);$('qr').src='https://api.qrserver.com/v1/create-qr-code/?size=190x190&data='+encodeURIComponent(link);$('paylink').href=link}
function placeOrder(e){e.preventDefault();let name=$('name').value.trim(),phone=$('phone').value.trim(),address=$('address').value.trim(),city=$('city').value.trim(),state=$('state').value.trim(),pin=$('pin').value.trim(),note=$('custom-note').value.trim(),txn=$('txn').value.trim();if(!/^[6-9]\d{9}$/.test(phone))return alert('Please enter a valid 10-digit mobile number.');if(!/^[1-9]\d{5}$/.test(pin))return alert('Please enter a valid 6-digit pincode.');if(payment==='upi'&&!txn)return alert('Please enter your UPI transaction/reference ID.');let items=cart.map((x,i)=>{let p=products.find(y=>y.id===x.id);return `${i+1}. ${p.name} × ${x.qty} = ${money(x.price*x.qty)}`}).join('\n');let msg=`Present Perfect Order\n\nCustomer: ${name}\nPhone: ${phone}\nAddress: ${address}, ${city}, ${state} - ${pin}\n\nProducts:\n${items}\n\nGrand Total: ${money(totals().total)}\nPayment: ${payment==='upi'?'UPI Paid':'Cash on Delivery'}${txn?'\nTransaction ID: '+txn:''}\nCustomization: ${note||'None'}`;window.open(`https://wa.me/${WA}?text=${encodeURIComponent(msg)}`,'_blank');cart=[];save();closeCheckout();alert('Your order is ready in WhatsApp. Tap Send to confirm.')}
document.addEventListener('DOMContentLoaded',()=>{render();renderReviews();save();$('search').oninput=render;$('cart-open').onclick=openCart;$('cart-close').onclick=closeCart;$('checkout-close').onclick=closeCheckout;$('cod').onclick=()=>{payment='cod';updatePayment()};$('upib').onclick=()=>{payment='upi';updatePayment()};$('checkout-form').onsubmit=placeOrder;$('copy-upi').onclick=()=>navigator.clipboard?.writeText(UPI).then(()=>alert('UPI ID copied: '+UPI));document.querySelectorAll('[data-filter]').forEach(a=>a.onclick=()=>{category=a.dataset.filter;render();document.querySelector('#shop').scrollIntoView({behavior:'smooth'})})});